// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/pres/PresBrowseRail.tsx": () => import("../components/mockups/pres/PresBrowseRail.tsx"),
  "./components/mockups/pres/PresHomeBrowseRail.tsx": () => import("../components/mockups/pres/PresHomeBrowseRail.tsx"),
  "./components/mockups/pres/PresHomeStacked.tsx": () => import("../components/mockups/pres/PresHomeStacked.tsx")
};
